/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clearingredundantfiles;

/**
 *
 * @author Enamul
 */
public class FileChooser extends javax.swing.JFrame {

    /**
     * Creates new form FileChooser
     */
    public FileChooser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        if (Outlook.working == 1) {
            Outlook.jTextField1.setText(Outlook.pathName[0] = jFileChooser1.getSelectedFile().toString());
        } else if (Outlook.working == 2) {
            Outlook.jTextField2.setText(Outlook.pathName[1] = jFileChooser1.getSelectedFile().toString());
        } else if (Outlook.working == 3) {
            Outlook.jTextField3.setText(Outlook.pathName[2] = jFileChooser1.getSelectedFile().toString());
        } else if (Outlook.working == 4) {
            Outlook.jTextField4.setText(Outlook.pathName[3] = jFileChooser1.getSelectedFile().toString());
        } else if (Outlook.working == 5) {
            Outlook.jTextField5.setText(Outlook.pathName[4] = jFileChooser1.getSelectedFile().toString());
        } else if (Outlook.working == 6) {
            Outlook.jTextField6.setText(Outlook.pathName[5] = jFileChooser1.getSelectedFile().toString());
        } else if (Outlook.working == 7) {
            Outlook.jTextField7.setText(Outlook.pathName[6] = jFileChooser1.getSelectedFile().toString());
        } else if (Outlook.working == 8) {
            Outlook.jTextField8.setText(Outlook.pathName[7] = jFileChooser1.getSelectedFile().toString());
        } else if (Outlook.working == 9) {
            Outlook.jTextField9.setText(Outlook.pathName[8] = jFileChooser1.getSelectedFile().toString());
        } else if (Outlook.working == 10) {
            Outlook.jTextField10.setText(Outlook.pathName[9] = jFileChooser1.getSelectedFile().toString());
        } else if (Outlook.working == 11) {
            Outlook.jTextField11.setText(Outlook.pathName[10] = jFileChooser1.getSelectedFile().toString());
        }

    }//GEN-LAST:event_jFileChooser1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                System.out.println(Thread.currentThread());
                new FileChooser().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
